--- #YAML:1.0
name:                POE-Component-ResourcePool-Resource-TokenBucket
version:             0.01
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Algorithm::TokenBucket:        0.32
    MooseX::POE:                   0.08
    POE::Component::ResourcePool:  0
    Test::use::ok:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
